In [4]:


import array
import numpy as np

#### https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.01-Understanding-Data-Types.ipynb

# Pyhton Array

In [3]:



L = list(range(10))
A = array.array('i', L)


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# integer array numpy array

In [6]:
a = np.array([3.14, 4, 2, 3])
print(a)


[3.14 4.   2.   3.  ]


Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):

In [8]:
a = np.array([1, 2, 3, 4], dtype='float32')
a[1]

2.0

In [20]:
#multidimensional array generator
a = np.array([range(i, i + 3) for i in [2, 4, 6]])
a = np.array([(i,i+3,i+5) for i in [2, 4, 6]])
([(i,i+3,i+5) for i in [2, 4, 6]])

[(2, 5, 7), (4, 7, 9), (6, 9, 11)]

# Creating arrays from Scratch


In [23]:
a = np.zeros(21,dtype=str)
a

array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', ''], dtype='<U1')

In [35]:
a = np.ones((10,20,30))
a[2,:,1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [36]:
np.full((3,3),1.66)

array([[1.66, 1.66, 1.66],
       [1.66, 1.66, 1.66],
       [1.66, 1.66, 1.66]])

In [ ]:
#creates 3.3 matrix array from random integers

In [38]:
a = np.random.normal(0, 1, (3, 3))
a

array([[ 1.18893194,  0.7459699 , -1.6253247 ],
       [-0.07294261, -0.41665126, -0.01943656],
       [ 1.08741052,  0.02202078, -0.81016624]])

# NumPy Standard Data Types